#pragma config(Motor,  motor1,          frontArmMotorTop, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor2,          frontArmMotorMiddle, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor3,          frontArmMotorBottom, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor4,          driveMotorLeftY, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor5,          frontIntake, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          backArmMotorTop, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor7,          backArmMotorMiddle, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor8,          backArmMotorBottom, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor9,          driveMotorRightBack, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor10,         driveMotorRightFront, tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wireless Controller to drive throwback.

  The tower of the bot is considered to be on the left-hand side of the bot.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.


------------------------------------------------------------------------------------------------*/

// Treat all 6 arm motors as a single motor, to avoid repetition in the main task
void setArmMotorSpeed(short armMotorSpeed)
{
	    // Both top motors
			motor[frontArmMotorTop] = armMotorSpeed;
			motor[backArmMotorTop] = armMotorSpeed;
			// Middle motors need to be driven backwards because there are 3 cogs in a row & they're the middle ones
			motor[frontArmMotorMiddle] = armMotorSpeed * -1;
			motor[backArmMotorMiddle] = armMotorSpeed * -1;
			// Both bottom motors
			motor[frontArmMotorBottom] = armMotorSpeed;
			motor[backArmMotorBottom] = armMotorSpeed;
}


task main()
{
	int threshold = 10;
	while(true)
	{
		//If the ChannelA (left Y-Axis) is greater than the threshold value,
		//then we'll set the speed of the motor to vlaue from the joystick.
		if(vexRT[Ch3] > threshold || vexRT[Ch3] < -threshold)
		{
			motor[driveMotorLeftY] = vexRT[Ch3];
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			motor[driveMotorLeftY] = 0;
		}

		//If the ChannelD (right Y-Axis) is greater than the threshold value,
		//then we'll set the speed of the motor to vlaue from the joystick.
		if(vexRT[Ch2] > threshold || vexRT[Ch2] < -threshold)
		{
			motor[driveMotorRightBack] = vexRT[Ch2];
			motor[driveMotorRightFront] = vexRT[Ch2];
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			motor[driveMotorRightBack] = 0;
			motor[driveMotorRightFront] = 0;
		}

		//If Button "R-Down" is pressed in, we'll set the arm motors to run in reverse.
		if(vexRT(Btn6D) == 1)
		{
			setArmMotorSpeed(-127);
		}
		//If the "R-Down" isn't pressed, but "R-Up" is, we'll set the motor to run forward.
		else if(vexRT[Btn6U] == 1)
		{
			setArmMotorSpeed(127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setArmMotorSpeed(-25);
		}
	}
}
