#pragma config(Motor,  motor1,          frontArmMotorTop, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor2,          frontArmMotorMiddle, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor3,          frontArmMotorBottom, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor4,          driveMotorLeftBack, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor5,          driveMotorLeftFront, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          backArmMotorTop, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor7,          backArmMotorMiddle, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor8,          backArmMotorBottom, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor9,          driveMotorRightBack, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor10,         driveMotorRightFront, tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wireless Controller to drive throwback.

  The tower of the bot is considered to be on the left-hand side of the bot.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.


------------------------------------------------------------------------------------------------*/

task main()
{
	int threshold = 10;
	while(true)
	{
		//If the ChannelA (left Y-Axis) is greater than the threshold value,
		//then we'll set the speed of the motor to vlaue from the joystick.
		if(vexRT[Ch3] > threshold || vexRT[Ch3] < -threshold)
		{
			setMotorSpeed(driveMotorLeftBack, vexRT[Ch3]);
			setMotorSpeed(driveMotorLeftFront, vexRT[Ch3]);
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			setMotorSpeed(driveMotorLeftBack, 0);
			setMotorSpeed(driveMotorLeftFront, 0);
		}

		//If the ChannelD (right Y-Axis) is greater than the threshold value,
		//then we'll set the speed of the motor to vlaue from the joystick.
		if(vexRT[Ch2] > threshold || vexRT[Ch2] < -threshold)
		{
			setMotorSpeed(driveMotorRightBack, vexRT[Ch2]);
			setMotorSpeed(driveMotorRightFront, vexRT[Ch2]);
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			setMotorSpeed(driveMotorRightBack, 0);
			setMotorSpeed(driveMotorRightFront, 0);
		}

		//If Button "R-Up" is pressed in, we'll set the arm motors to run in reverse.
		if(vexRT(Btn6U) == 1)
		{
			setMotorSpeed(frontArmMotorTop, -127);
			setMotorSpeed(frontArmMotorMiddle, -127);
			setMotorSpeed(frontArmMotorBottom, -127);
			setMotorSpeed(backArmMotorTop, -127);
			setMotorSpeed(backArmMotorMiddle, -127);
			setMotorSpeed(backArmMotorBottom, -127);
		}
		//If the "R-Up" isn't pressed, but "R-Down" is, we'll set the motor to run forward.
		else if(vexRT[Btn6D] == 1)
		{
			setMotorSpeed(frontArmMotorTop, 127);
			setMotorSpeed(frontArmMotorMiddle, 127);
			setMotorSpeed(frontArmMotorBottom, 127);
			setMotorSpeed(backArmMotorTop, 127);
			setMotorSpeed(backArmMotorMiddle, 127);
			setMotorSpeed(backArmMotorBottom, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(frontArmMotorTop, 0);
			setMotorSpeed(frontArmMotorMiddle, 0);
			setMotorSpeed(frontArmMotorBottom, 0);
			setMotorSpeed(backArmMotorTop, 0);
			setMotorSpeed(backArmMotorMiddle, 0);
			setMotorSpeed(backArmMotorBottom, 0);
		}

		////If Button "L-Up" is pressed in, we'll set the arm motor to run in reverse.
		//if(vexRT(BtnRUp) == 1)
		//{
		//	setMotorSpeed(clawMotor, -127);
		//}
		////If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		//else if(vexRT(BtnRDown) == 1)
		//{
		//	setMotorSpeed(clawMotor, 127);
		//}
		//else	//If neither button is pressed, we'll set the motor off.
		//{
		//	setMotorSpeed(clawMotor, 0);
		//}
	}
}
